export const EMPLOYEES_LOADED = "Employees/EMPLOYEES_LOADED";
export const EMPLOYEE_ADDED = "Employees/EMPLOYEE_ADDED";
export const FETCHING_EMPLOYEES = "Employees/FETCHING_EMPLOYEES";
export const EMPLOYEES_FETCHED = "Employees/EMPLOYEES_FETCHED";
export const EMPLOYEES_FETCHED_ERROR = "Employees/EMPLOYEES_FETCHED_ERROR"
